language: node_js
node_js:
  - '6'

cache:
  directories:
  - node_modules

services:
  - docker

before_install:
  - npm install -g ionic cordova

script:
  - rm -rf www/
  - npm run ionic:build --prod --aot --minifyJs --minifyCss --optimizeJs
  - docker build -t pacworx/app-test .

after_success:
  - ionic upload -e $IONIC_EMAIL -p $IONIC_PASS
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USER" -p="$DOCKER_PASS"
  - docker push pacworx/app-test

notifications:
  slack: pacworx:M2sZGPNSvxzvLD4XkaUF4oGI
