language: node_js
node_js:
  - '6'

cache:
  directories:
  - node_modules

before_install:
  - npm install -g ionic cordova

script:
  - ionic build

after_success:
  - ionic login --email $IONIC_EMAIL --password $IONIC_PASS
  - ionic upload
